package org.vaadin.example.rsa.match;

import org.vaadin.example.rsa.quad.HasPoint;

/**
 * A Location in 2D space defined by the given pair of doubles.
 * @param x coordinate
 * @param y coordinate
 * <p>
 * The implementations of {@link #equals(Object)}, {@link #hashCode()}, and {@link #toString()}
 * are automatically generated by the compiler and operate on the record components {@link #x()} and {@link #y()}.
 * @author José Paulo Leal {@code jpleal@fc.up.pt}
 * @author Maria Pereira
 */
public record Location(double x, double y) implements HasPoint {
    /**
     * Creates an instance of a Location record class.
     @param x the value for the x record component
     @param y the value for the y record component
     */
    public Location(double x, double y){
        this.x = x;
        this.y = y;
    }
}
